### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by August-Alm** [VictorTaelin/Interaction-Type-Theory#2]
Wonderful ideas! What is the status of this project? If it is abandoned, could you please update the README with some comments as to why?
Best wishes,
August

**Comment by VictorTaelin** [comment]
Not abandoned, I've just stopped a white to work on HVM2. Sadly I'm only one so I always need to split my attention through a bunch of interesting / promising things. ITT is definitely the most important specially because I believe a higher-order unifier on it could make for the best automated reasoning engine in the world. But HVM2's massive parallel runtime is important too, as are the other projects...

Regarding the status, I stopped after I solved the main issues regarding encoding encoding dependent types and thus finally understood how type checking is supposed to be done - see the last post on the closed issue here. So now basically I'm convinced it works and waiting for an opportunity/time to start thinking about it again.
